---
name: Unit Tests
on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

concurrency:
  group: 'unit-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'
      - run: bash scripts/gogetcookie.sh
      - run: make fmt
        env:
          GITHUB_ACTIONS_STAGE: "UNIT_TESTS"
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: $GITHUB_WORKSPACE
